### ISSUE TITLE
Build in Cloud Run

### ISSUE THREAD

**Issue by jskeet** [nodatime/nodatime.org#168]
If we can get this to build and push in Cloud Run (triggered by a change in any repo) it'll be a lot simpler than maintaining bagpuss.

**Comment by jskeet** [comment]
Currently building in an Ubuntu VM is failing with:

```sh
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'operator /' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at DocfxYamlLoader.DocfxMember.get_DisplayName() in /home/jonathan_skeet/github/nodatime.org/build/DocfxYamlLoader/DocfxMember.cs:line 50
   at ReleaseDiffGenerator.Program.WriteBullet(TextWriter writer, DocfxMember member, Boolean link, String obsoleteSuffix) in /home/jonathan_skeet/github/nodatime.org/build/ReleaseDiffGenerator/Program.cs:line 158
   at ReleaseDiffGenerator.Program.WriteChanges(TextWriter writer, IEnumerable`1 members, String label, Boolean link, String obsoleteSuffix) in /home/jonathan_skeet/github/nodatime.org/build/ReleaseDiffGenerator/Program.cs:line 127
   at ReleaseDiffGenerator.Program.GenerateDiffs(Release oldRelease, Release newRelease, String destination) in /home/jonathan_skeet/github/nodatime.org/build/ReleaseDiffGenerator/Program.cs:line 80
   at ReleaseDiffGenerator.Program.Main(String[] args) in /home/jonathan_skeet/github/nodatime.org/build/ReleaseDiffGenerator/Program.cs:line 33
```

Need to investigate...
